# Write Kubernetes Deployment Script
#kubernetes api version for deployment
apiVersion: apps/v1

#defines deployment resource
kind: Deployment

#metdata for the deployment with name book-catalog-deployment
metadata:
  name: book-catalog-deployment
  #specifies one replica for our application
spec:
  replicas: 1

  #defines how the deployment finds pods to manage
  selector:
    matchLabels:
      app: book-catalog

  #template for creating pods,labelled with app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
  
  #specifies container details using book-catalog:latest image
    spec:
      containers:
      - name: book-catalog
        image: book-catalog:latest
        #tells kubernetes never to pull the image as its available locally
        imagePullPolicy: Never
        #exposes port 8000 from the container
        ports:
        - containerPort: 8000
        #sets an enviroment variable for the connection string
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_ck_user:1Agmwj5O4bjUxqilFNyNfIaafiCy1Xpr@dpg-cr26qk3tq21c73flnolg-a.oregon-postgres.render.com/sit722_ck"
